#!/bin/bash
set -euo pipefail

# Kubernetes master private IP
MASTER_IP="10.0.1.10"

# Retrieve the join command generated by the master
scp -o StrictHostKeyChecking=no \
    ec2-user@${MASTER_IP}:/home/ec2-user/join-worker.sh \
    /tmp/join-worker.sh

# Make the downloaded script executable
chmod +x /tmp/join-worker.sh

# Join this worker node to the Kubernetes cluster
sudo /tmp/join-worker.sh

# Remove the join command after successful use
rm -f /tmp/join-worker.sh

echo "Worker node successfully joined the Kubernetes cluster."